name: 'HTML Preview'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'NL17.html'

#name: 'HTML Preview'
#author: 'Pavitra Golchha | @pavi2410'
#description: 'Preview HTML page in PR'
#inputs:
#  msg:
#    description: 'The message to display on PR comment'
#    required: true
#    default: 'Click here to preview HTML page in browser'
#  html_file:
#    description: 'The HTML file you want to preview'
#    required: true
#    default: 'NL17.html'
#  gh_token:
#    description: 'GitHub Token'
#    required: true
#    default: ${{ github.token }}
#runs:
#  using: 'node12'
#  main: 'dist/index.js'
#branding:
#  color: 'orange'
#  icon: 'eye'
#